# Report month start
START?=		01
# Report month end
STOP?=		03
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	1

# Entries from the various official and semi-official teams
TeamReports= foundation.md core.md releng.md clusteradm.md ci.md portmgr.md office_hours.md

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= azure.md git.md lua.md linuxulator.md nfsovertls.md

# Changes affecting the base system and programs in it
Userland= bc-dc.md binutils.md rtld.md vhdx.md

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= ausoc-audio.md bluetooth.md drm.md dts.md ena.md forciblyunmount.md imx8m.md iwlwifi.md la57.md largepages.md ls1046.md pvlist.md routing.md zstd.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= cheribsd.md multiarch-ci.md riscv.md

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation= weblate.md

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= FreshPorts.md bastille.md kde.md haskell.md rtsx.md valgrind.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= bhyve-intel-openbsd.md bhyve-nvme.md chaifi.md mixertui.md potluck.md

# Objects that defy categorization
Miscellaneous= sage.md

.include <../tools/Makefile>
