== BSDDialog - TUI Widgets

Link: link:https://gitlab.com/alfix/bsddialog[BSDDialog Project] +
Link: link:https://invisible-island.net/dialog[Dialog Project] +
Link: link:https://wiki.freebsd.org/GPLinBase[GPLinBase Wiki Page] +
Link: link:https://man.freebsd.org/dialog4ports/1[dialog4ports utility]

Contact: Alfonso Sabato Siciliano <alfonso.siciliano@email.com>  

The purpose of this project is to provide an utility and a library to build
scripts and tools with UI Widgets in a terminal.
The project is inspired by Dialog; however BSDDialog is released under the terms
of the BSD-2-Clause License while Dialog is licensed as LGPL so a link of the
project has been added to the "GPL Software in the Base System" wiki page.

The aim is to provide full compatibility with the dialog utility (the challenge
is to implement over seventy options and almost thirty widgets).
The API compatibility with the library is not a priority because libbsddialog
should meet FreeBSD's needs, for example it provides the new mixedlist()
function, it can take as argument a set of: checklists, radiolists and
separators, so it could be useful for building a dialog4ports clone: more easier
to implement and not depending on non-permissive dependencies.

BSDDialog is currently under development, no widget is really completed
(autosizing, resizing and scrolling are missing), nevertheless runnable examples
for the utility and the library are inside the example folders and described in
the README.

Finally, a curiosity: BSDDialog started from the MixerTUI code base, however the
original code has been almost completely rewritten.
