=== Documentation Engineering Team

Link: link:https://www.freebsd.org/docproj/[FreeBSD Documentation Project] +
Link: link:https://docs.freebsd.org/en/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors] +
Link: link:https://www.freebsd.org/administration/#t-doceng[Documentation Engineering Team]

Contact: FreeBSD Doceng Team <doceng@FreeBSD.org> +

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project, more infomation on link:https://www.freebsd.org/internal/doceng/[FreeBSD Doceng Team Charter].

During the last quarter, we welcomed back Ceri Davies (ceri@) as a doc committer. Sergio Carlavilla (carlavilla@) and Danilo G. Baio (dbaio@) joined the doceng@ team.

A new article was included in the FreeBSD Documentation by Ka Ho Ng (khng@), link:https://docs.freebsd.org/en/articles/freebsd-src-lsp/[Use Language Servers for Development in the FreeBSD Src Tree].

Much work was done regarding the transition to Hugo/Asciidoctor, but there are still pending issues in the FreeBSD Documentation Project after the migration.
We thank everyone who is helping to find and fixing them.
The link:https://wiki.freebsd.org/Doc/IdeaList[TODO items] wiki list was refreshed, and everyone is welcome to contribute to it.

==== FreeBSD Translations on Weblate

Link: link:https://wiki.freebsd.org/Doc/Translation/Weblate[Translate FreeBSD on Weblate] +
Link: link:https://translate-dev.freebsd.org/[FreeBSD Weblate Instance]

The Weblate project link:https://translate-dev.freebsd.org/projects/documentation/[Documentation (Books and Articles)] is open to the public.

The Automatic Translation feature was executed in all languages, re-using translations from the former project (Docbook).

There are still pending issues about the new translation process, and the status can be seen on link:https://wiki.freebsd.org/Doc/IdeaList#Translation[IdeaList#Translation].

Website translations weren't released through Weblate yet. So we decided to hold it until we have more details about the working group that will redesign the Website and the Documentation Portal, to avoid re-work.

==== FreeBSD Website Revamp - WebApps working group

Contact: Sergio Carlavilla <carlavilla@FreeBSD.org>

Working group in charge of creating the new FreeBSD Documentation Portal; and redesigning the FreeBSD main Website and its components.
FreeBSD developers can follow and join the working group on the FreeBSD Slack channel #wg-www21.
The work will be divided into four phases:

. Redesign of the Documentation Portal
+
Create a new design, responsive and with global search. (_Work in progress_)

. Redesign of the Manual Pages on Web
+
Scripts to generate the HTML pages using mandoc. (_Not started_)

. Redesign of the Ports page on Web
+
Ports scripts to create an applications portal. (_Not started_)

. Redesign of the FreeBSD main Website
+
New design, responsive and dark theme. (_Not started_)
