== Status Report Sample - This Will Become The Title

Link: link:http://www.example.com/project/url[Link description here]  

Link:	link:http://freshports.org/[FreshPorts]
Link:	link:http://news.freshports.org/[FreshPorts blog]

Contact: Dan Langille <dvl@FreeBSD.org>  

FreshPorts, and its sister site, FreshSource, have reported
upon FreeBSD commits for 20 years. They cover all commits,
but its primary focus is ports.

FreshPorts tracks the commits and extracts data from the
port Makefiles to create a database of information useful
to both port developers and port users.

For example, link:https://www.freshports.org/security/acme.sh/[https://www.freshports.org/security/acme.sh/] shows
the history of this port, back to its creation in May 2017.

### git ###

The transition from subversion to git went superbly. Now the work
is concentrating on branches. We are close to incorporating all branches
(on src, doc, and ports) into the website.

The website now queries the main repo every three minutes and pulls in updates.
Commit processing under git is faster and more reliable.  Creating the XML
directly from git and not from parsing commit emails has its benefits.

### Help wanted ###

Since the link:last report[https://www.freebsd.org/status/report-2020-10-2020-12.html#FreshPorts],
link:Jethro Nederhof[https://github.com/jethron] has been 
doing fantastic work bringing the website up to HTML5 and into the modern world.
Nothing dramatic, from what the users see, as it has been mostly behind-the-scenes.

We can always use more helpers. The website mostly runs itself and requires very little
on-going maintence (pkg upgrades, OS patche, etc). Most of the work is designing new
features, fixing bugs, identifying issues, and discussion with users. Changes to the ports
tree usually don't affect the website much.

Tasks include:

* There is a long list of link:https://github.com/FreshPorts/freshports/issues[issues]
for the website.

* The link:https://github.com/FreshPorts/git_proc_commit/issues[git_proc_commit project]
also has a set of issues, mostly in Pyton, some perhaps related to the website.

* Documentation outlining how the various project fit together and how they work is 
required

* I have some subversion repos which should be converted to git and uploaded to GitHub.
This would allow people to work on the backend code (commit ingress and processing).

* The FreshSource website could be updated to modern standards and the repo converted to git.

Thank you
