== Ports Collection

Link: link:https://www.FreeBSD.org/ports/[About FreeBSD Ports]
Link: link:https://docs.freebsd.org/en/articles/contributing/ports-contributing/[Contributing to Ports]
Link: link:http://portsmon.freebsd.org/[FreeBSD Ports Monitoring]
Link: link:https://www.freebsd.org/portmgr/[Ports Management Team]
Link: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball]

Contact: René Ladan <portmgr-secretary@FreeBSD.org>  
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>  

Paragraphs are separated with an empty line. Use AsciiDoctor syntax, the same as you use on GitHub.
If you don't know AsciiDoctor, just write it as if it was plain text.

Show the importance of your work.
Status reports are not just about telling everyone that things were done, they also need to explain why they were done.

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages, and personnel matters.
Below is what happened in the last quarter.

* #ports #PR #PRunassigned #commits #committers conclusion
* commit bits granted/safekept (who/why)
* portmgr news/members
* infra: USES, default-versions, big changes
* major port updates (pkg), Firefox, Chromium
* exp-runs, pkg-builders, other infra

If help is needed, make this explicit.
List tasks, with enough detail that people know if they are likely to be able to do them, and invite people to get in contact:

* Help for PRs?
* Help for testing?
* Help for documentation?
