FreeBSD Quarterly Status Reports
================================

### Drafts

This repository is for drafts.

Please submit your draft as early as possible. To submit:

1. Fork the repository - reusing an old fork is OK.
2. Create a new branch and enter the directory for the current time
   period - `2021q4`.
3. Create a new file, with a name that corresponds with the name of
   your project - use the `report-sample.adoc` template.
4. Create a pull request.
5. Someone will review it and may request changes. If they do,
   evaluate the requests, make any you think are warranted, explain
   any you chose not to, and push again. *Do not squash or
   force-push* if at all possible as this makes the next review
   much harder.
6. Once your draft is accepted and merged, you're good.

You can tweak things after your draft was merged. Simply edit, then
submit another PR.

Please do not worry excessively about language errors or AsciiDoc
syntax - we can correct things for you.

#### Deadline for submissions for `2021q4`

30th of December 2021

Note that this is **immediately** after the end of the quarter.

General rules for deadlines:

* Reports will be collected during the third month of each quarter.
* Deadlines will be the 1st of January, April, July and October.
* Deadlines for portmgr are 1 week after the official deadlines:
  8th of January, April, July and October.
* Late report submitters can ask for 1 more week of time after
  deadlines by contacting the quarterly status reports team, for
  example by sending an e-mail to quarterly-submissions@.

### Finals

Collated final reports are:

* Listed at [FreeBSD Status Reports](https://www.freebsd.org/news/status/).
* Promoted through [newsflashes](https://www.freebsd.org/news/newsflash/).

The most recent report:

* https://www.freebsd.org/status/report-2021-07-2021-09/
