=== FreeBSD on Microsoft HyperV and Azure

Links: +
link:https://wiki.freebsd.org/MicrosoftAzure[Microsoft Azure article on FreeBSD wiki] URL: link:https://wiki.freebsd.org/MicrosoftAzure[] +
link:https://wiki.freebsd.org/HyperV[Microsoft HyperV article on FreeBSD wiki] URL: link:https://wiki.freebsd.org/HyperV[]

Contact: Microsoft FreeBSD Integration Services Team <bsdic@microsoft.com> +
Contact: link:https://lists.FreeBSD.org/mailman/listinfo/freebsd-cloud[freebsd-cloud Mailing List] +
Contact: The FreeBSD Azure Release Engineering Team <releng-azure@FreeBSD.org> +
Contact: Wei Hu <whu@FreeBSD.org> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org> +

The link:https://azuremarketplace.microsoft.com/marketplace/apps/thefreebsdfoundation.freebsd-13_1[13.1-RELEASE image on Azure Marketplace] has been published.

Work in progress tasks:

* Automatizing the image building and publishing process
* Build and publish ZFS-based image to Azure Marketplace
** The taks will be benefited by merging of ZFS support of makefs(8) and release(7)
*** https://reviews.freebsd.org/D23334
*** https://reviews.freebsd.org/D34426
*** https://reviews.freebsd.org/D35248
* Build and publish gen2 vm image to Azure Marketplace
** Blocked by https://bugs.freebsd.org/264267

Above tasks are sponsored by The FreeBSD Foundation, with resources provided by Microsoft.

Wei Hu and his colleagues in Microsoft are working on several tasks sponsored by Microsoft:

* Fixing booting issue on gen2 vm in Azure
** https://bugs.freebsd.org/264267
* Porting Hyper-V guest support to aarch64

Open tasks:

* Update FreeBSD related doc at link:https://docs.microsoft.com[]
* Support FreeBSD in link:https://azure.microsoft.com/services/devops/pipelines/[Azure Pipelines]
* Update link:https://www.freshports.org/sysutils/azure-agent[Azure agent port] to the latest version
* Upstream link:https://github.com/Azure/WALinuxAgent/pull/1892[local modifications of Azure agent]
