=== blued

Links: +
link: https://git.lysator.liu.se/kempe/blued[blued git] URL: https://git.lysator.liu.se/kempe/blued[https://git.lysator.liu.se/kempe/blued]

Contact: +
Mail: kempe@lysator.liu.se +
IRC: kempe@libera.chat

==== Introduction

The aim of blued is to provide a bluetooth daemon with an IPC
interface that allows for a user friendly way for an unprivileged user
to connect and use bluetooth devices.

Work began after having issues with my bluetooth mouse and figuring
out that the problem was a lack of support for secure simple pairing.
This then sent me down the rabbit hole of working on my own bluetooth
daemon.

==== blued - what is it?

blued consists of three parts: a library, a daemon and a command line
utility. The library abstracts away bluetooth details, the daemon
manages bluetooth devices and the command line utility communicates
with the daemon via a UNIX socket.

The difference between blued and the existing bluetooth software, i.e.
bthidd and hcsecd, is first and foremost supporting secure simple
pairing, but also providing an IPC. A long term goal is to provide a
graphical user interface that can list devices and provide a simple
one-click setup to connect them.

With the current version of blued, it supports scanning for devices
and pairing with them. To get a HID device to work, bthidd is still
needed. A script is provided to pair a bluetooth device and
appropriately configure bthidd.

If the supplied script works as expected, your mouse will get
connected, paired and simply start working. If the mouse is turned off
and on again, the blued daemon should let it reconnect without user
intervention.

Once pairing has proven stable and bugs have been ironed out, the plan
is for work to start an integrating bthidd with/into blued in some way
to have HID devices automatically start functioning when paired
without the use of an external script.


==== What is needed to use blued v0.1?

You need the optional `src` component installed in [.filename]#/etc/src#.

First, make sure link:https://docs.freebsd.org/en/books/handbook/advanced-networking/#network-bluetooth[you have working Bluetooth drivers loaded as explained in the FreeBSD handbook].

To test blued, fetch link:https://git.lysator.liu.se/kempe/blued/-/releases/v0.1[the blued v0.1 source code].
Then compile it, patch your FreeBSD kernel with the patches in
[.filename]#kernel_patches#, and recompile the `hci` module as
explained in [.filename]#README#.

blued has primarily been tested on FreeBSD 12.3, but my patches
applied cleanly on 13.1 when I tested. I am not supplying a port at the moment, but it is possible to run the
software straight from the build directory or run "make
install" that will install all needed files. Both blued and bluecontrol
use capsicum and blued can be configured to drop its root privileges.

For more information, refer to the `Running blued` section of [.filename]#README#.

==== Feedback!

I have only tried this software with my own mouse and realise that a
sample size of one single bluetooth device is pretty small. I'm
expecting issues and am greatly looking forward to feedback from
others!

In case of trouble, output from /var/log/debug.log and
/var/log/messages as well as a traffic dump from "hcidump -x" while
trying to pair will help with troubleshooting.

If you want to get involved with the code and submit patches, you're
welcome to link:https://git.lysator.liu.se/kempe/blued[visit the repository]
on Lysator's Git.

Thank you for reading! +
Cordially,
Andreas Kempe
