=== Linux compatibility layer update

Contact: Dmitry Chagin, <dchagin@FreeBSD.org>
Contact: Edward Tomasz Napierala, <trasz@FreeBSD.org>

The goal of this project is to improve FreeBSD's ability to execute unmodified Linux binaries.
Current support status of specific Linux applications is being tracked at the link:https://wiki.freebsd.org/LinuxApps[Linux app status Wiki page].

Implementation of the Y2k38 Linux project is mostly finished, all '*_time64()' system calls are commited.

The state of the arm64 Linux emulation layer is brought to the state of amd64 Linux emulation layer.
I.e., implemented the vDSO, machine dependend futexes, signals delivery.

The thread affinity system calls are modified to implement Linux semantics.

In total, over 50 bugs fixed, glibc-2.35 tests suite reports less than 80 failed tests.

All changes in the Linux emlation layer are merged to the stable/13 branch.

Initial support for fancy Linux system call tracing has been added to the libsysdecode and kdump.
There is ongoing work to make tracing more syscalls.


Sponsor: EPSRC (Edward’s work)
