# Report month start
START?=		10
# Report month end
STOP?=		12
# Report year
YEAR?=		2019
# Report quarter
QUARTER?=	4

# Entries from the various official and semi-official teams
TeamReports= core.md foundation.md re.md clusteradm.md ci.md

# Projects that span multiple categories, from the kernel and userspace to
# the Ports Collection or external projects
Projects= esn.md nfs42.md dts.md rockchip.md mkova.md

# Changes affecting the base system and programs in it
Userland= linuxulator.md

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= ausoc-audio.md azure.md ec2-arm.md ena.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= powerpc.md  ls1046.md

# Noteworthy changes in the documentation tree or new external
# books/documents
Documentation=

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= portmgr.md kde.md java.md electronjs.md bastille.md upt.md wine.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= sysctlbyname-improved.md nomad-pot-driver.md 7-days-challenge.md nomadbsd.md

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
