# Copyright (c) 2022 Lorenzo Salvadore <salvadore@FreeBSD.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

check_pluses:
	@${ECHO_CMD} ${SEPARATOR_STRING}
	@${ECHO_CMD} "Search for pluses:"
	@${ECHO_CMD} ${SEPARATOR_STRING}
	@for report in ${ALL_REPORTS} intro.adoc; \
	do \
		${ECHO_CMD} -n "$$report..."; \
		lines="$$( \
			${GREP_CMD} -E '\+[^$$]|[^ ]\+$$' $$report | \
			${GREP_CMD} -v '^[^+]*link:[^ ]*\[[^+]*$$' || \
			${TRUE_CMD})"; \
		if test -n "$$lines"; \
		then \
			${ECHO_CMD} "${WARNING_STRING} please check the following lines:"; \
			${ECHO_CMD} "$$lines"; \
		else \
			${ECHO_CMD} "looks fine."; \
		fi \
	done

fix_pluses:
	@${ECHO_CMD} ${SEPARATOR_STRING}
	@${ECHO_CMD} "Warning: This fix assumes no more than two consecutives + signs are found."
	@${ECHO_CMD} "If you have lines with more than two consecutive + signs, you need to fix them manually."
	@${ECHO_CMD} "You also need to fix manually lines that have + signs both in links and outside links."
	@${ECHO_CMD} -n "Fixing pluses..."
	@for report in ${ALL_REPORTS} intro.adoc; \
	do \
		lines="$$( \
			${GREP_CMD} -E '\+[^$$]|[^ ]\+$$' $$report | \
			${GREP_CMD} -v 'link:[^ ]*\[' || \
			${TRUE_CMD})"; \
		lines="$$( \
			${ECHO_CMD} "$$lines" | ${TR_CMD} ' \n' 'э ')"; \
		for line in $$lines; \
		do \
			line="$$( \
				${ECHO_CMD} "$$line" | \
				${TR_CMD} 'э ' ' \n')"; \
			line_regexp="$$( \
				${ECHO_CMD} "$$line" | \
				${SED_CMD} -E 's,[.$$|[*+?\^/],\\&,g')"; \
			echo "$$line"; \
			echo "$$line_regexp"; \
			${SED_CMD} -i '' "/$$line_regexp/s,\([^+]\)\+\+\([^+]\),\1{plus}{plus}\2,g" $$report; \
			line="$$(${ECHO_CMD} "$$line" | \
				${SED_CMD} 's,\([^+]\)\+\+\([^+]\),\1{plus}{plus}\2,g')"; \
			line_regexp="$$( \
				${ECHO_CMD} "$$line" | \
				${SED_CMD} -E 's,[.$$|[*+?\^/],\\&,g')"; \
			echo "$$line"; \
			echo "$$line_regexp"; \
			${SED_CMD} -i '' "/$$line_regexp/s,\([^+]\)\+\([^+]\),\1{plus}\2,g" $$report; \
		done \
	done
	@${ECHO_CMD} "done."
	@${ECHO_CMD} ${SEPARATOR_STRING}
