# Report month start
START?=		07
# Report month end
STOP?=		09
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	3

# Entries from the various official and semi-official teams
TeamReports= foundation.md releng.md clusteradm.md ci.md portmgr.md office.md graphics.md

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= azure.md crossbuilding.md git.md linuxulator.md lldb.md lua.md nfsovertls.md syzkaller.md

# Changes affecting the base system and programs in it
Userland= 

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= drm.md dts.md if_dwc.md ebpf.md ena.md esn.md ls1046.md powerpc64le.md ure-update.md vxlan.md wifi.md zstd.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= cheribsd.md riscv.md

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation= docng.md

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= grub-bhyve.md kde.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= potluck.md puppet.md

# Objects that defy categorization
Miscellaneous= 

.include <../tools/Makefile>
