# Report month start
START?=		07
# Report month end
STOP?=		09
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	3

# Entries from the various official and semi-official teams
TeamReports= clusteradm.md releng.md ci.md portmgr.md office.md

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= lua.md crossbuilding.md nfsovertls.md azure.md linuxulator.md lldb.md

# Changes affecting the base system and programs in it
Userland= kde.md 

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= vxlan.md wifi.md drm.md dts.md if_dwc.md ebpf.md ena.md esn.md ls1046.md powerpc64le.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= riscv.md cheri.md

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation= 

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= grub-bhyve.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= potluck.md puppet.md

# Objects that defy categorization
Miscellaneous= 

.include <../tools/Makefile>
