# Report month start
START?=		10
# Report month end
STOP?=		12
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	4

# Entries from the various official and semi-official teams
TeamReports= ci.md clusteradm.md portmgr.md releng.md officehours.md

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= linuxulator.md lldb.md netapp.md nfsovertls.md openbsm.md 

# Changes affecting the base system and programs in it
Userland= ping.md

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= ena.md iwlwifi.md random-fx.md pf.md routing-lookups.md routing-multipath.md thunderbolt.md zstd.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= riscv.md

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation= weblate.md

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= kde.md office.md xfce.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= aarch64-vmware.md bastille.md embedded-lab.md FreshPorts.md k8s-bhyve.md puppet.md 

# Objects that defy categorization
Miscellaneous= nfs-exporter.md

.include <../tools/Makefile>
