# Report month start
START?=		10
# Report month end
STOP?=		12
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	4

# Entries from the various official and semi-official teams
TeamReports= FreeBSD-Foundation.md releng.md clusteradm.md ci.md portmgr.md officehours.md

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= basegpl.md git.md linuxulator.md lldb.md netapp.md nfsovertls.md openbsm.md toolchain.md

# Changes affecting the base system and programs in it
Userland= ping.md

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= ena.md iwlwifi.md random-fx.md pf.md routing-lookups.md routing-multipath.md thunderbolt.md vectored-aio.md zstd.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= aarch64-foundation.md riscv.md

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation= weblate.md docng.md

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= kde.md office.md ports_non_x86.md python27-removal.md xfce.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= aarch64-vmware.md bastille.md cheribsd.md embedded-lab.md FreshPorts.md hellosystem.md k8s-bhyve.md puppet.md

# Objects that defy categorization
Miscellaneous= nfs-exporter.md

.include <../tools/Makefile>
