=== FreeBSD Foundation

Links: +
link:https://www.FreeBSDfoundation.org[FreeBSD Foundation] URL: link:https://www.FreeBSDfoundation.org[https://www.FreeBSDFoundation.org] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[https://FreeBSDFoundation.org/blog/technology-roadmap/] +
link:https://www.FreeBSDfoundation.org/donate/[Donate] URL: link:https://www.FreeBSDfoundation.org/donate/[https://www.FreeBSDFoundation.org/donate/] +
link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program[https://www.FreeBSDFoundation.org/FreeBSD-foundation-partnership-program] +
link:https://www.FreeBSDfoundation.org/journal/[FreeBSD Journal] URL: link:https://www.FreeBSDfoundation.org/journal/[https://www.FreeBSDFoundation.org/journal/] +
link:https://www.FreeBSDfoundation.org/news-and-events/[Foundation News and Events] URL: link:https://www.FreeBSDfoundation.org/news-and-events/[https://www.FreeBSDFoundation.org/news-and-events/] +

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated
to supporting and promoting the FreeBSD Project and community
worldwide. Donations from individuals and corporations are used to fund
and manage software development projects, conferences, and developer
summits. We also provide travel grants to FreeBSD contributors, purchase
and support hardware to improve and maintain FreeBSD infrastructure, and
provide resources to improve security, quality assurance, and release
engineering efforts. We publish marketing material to promote, educate,
and advocate for the FreeBSD Project, facilitate collaboration between
commercial vendors and FreeBSD developers, and finally, represent the
FreeBSD Project in executing contracts, license agreements, and other
legal arrangements that require a recognized legal entity.

Here are some highlights from the Foundation for the first quarter of
2022.

==== Fundraising Efforts

As promised, we have updated out fundraising meter for 2022.  So far, we
have raised $80,519 from 201 different donations towards our 2022 goal
of $1,400,000.  We currently have one gold sponsor, Facebook, and one
silver sponsor, VMware.  The companies that donate free hosting for the
Project are: Bytemark, NextArray, NYI, and Sentex Data Communications.
We also receive free hosting from the Computer Science Department at
NCTU.

If you want to help us continue our efforts, please consider making a
donation towards our 2022 fundraising campaign!
https://www.FreeBSDFoundation.org/donate/.

We also have a Partnership Program for larger commercial donors. You can
read about it at
https://www.FreeBSDFoundation.org/FreeBSD-foundation-partnership-program/.


==== OS Improvements

During the first quarter of 2022, 372 src, 41 ports, and 16 doc tree
commits were made that identified The FreeBSD Foundation as a sponsor.
# This represents 16, 0.4, and 5% of the total number of commits in each repository.

You can read about Foundation-sponsored projects in individual quarterly report
entries:

- Crypto changes for WireGurard
- Intel Wireless driver support

Here is a small sample of other base system improvements from Foundation
developers this quarter that do not have separate report entries.

==== riscv: Add support for enabling SV48 mode

SV48 is intended for systems for which a 39-bit virtual address space is
insufficient.  This change increases the size of the user map from 256GB
to 128TB.  The kernel map is left unchanged for now.

For now SV48 mode is left disabled by default, but can be enabled with a
tunable.  Note that extant hardware does not implement SV48, but QEMU
does.

- In pmap_bootstrap(), allocate a L0 page and attempt to enable SV48
  mode.  If the write to SATP doesn't take, the kernel continues to run
  in SV39 mode.
- Define VM_MAX_USER_ADDRESS to refer to the SV48 limit.  In SV39 mode,
  the region [VM_MAX_USER_ADDRESS_SV39, VM_MAX_USER_ADDRESS_SV48] is not
  mappable.

==== Add v3 support to CTF tools

CTF, the Compact C Type Format, is a representation of type information
most often contained within ELF binaries.  This type information is
helpful for probing tools like DTrace.  Recent work by Mark Johnston
allows different Dtrace providers like the FBT (Function Boundary
Tracing) provider to work with version 3 of CTF.

==== FreeBSD on the Framework Laptop

Two Foundation staff members, Ed Maste and Mark Johnston, as well as a few developers and community members now each have access to Framework laptops, which are designed to make hardware upgrades, repairs, and customizations straightforward for the average user.  The goal of this work is to ensure that the experience running FreeBSD on the laptops matches the stability that FreeBSD users expect.

Recent improvements and fixes include:
 making audio switch appropriately between speakers and the headphone jack when headphones are plugged in or unpluged
A fix for bug 259230, which would cause a Framework laptop to reboot or power off when the touchpad was used.
Adding the Tempo Semiconductor 92HD95B HDA codec ID
A temporary fix for stalling usb enumeration, bluetooth, and S3 resume.  The temporary fix is to avoid attaching to several newer Intel controllers, which require firmware to be loaded, which is different from that implemented by ng_ubt_intel and iwmbtfw, so they are not usable yet.
Avoid a 16 second boot delay, by probing the TSC frequency earlier.  This lets us use the TSC to implement early DELAY, limiting the use of the sometimes-unreliable 8254 PIT.

You can follow news about FreeSD work on the Framework laptop at: https://wiki.freebsd.org/Laptops/Framework_Laptop.

==== Continuous Integration and Quality Assurance

The Foundation provides a full-time staff member and funds projects to improve
continuous integration, automated testing, and overall quality assurance efforts
for the FreeBSD project.

==== Supporting FreeBSD Infrastructure

The Foundation provides hardware and support for the Project.  At the
time of writing, the server that will become the new Australian mirror
has arrived in Australia, has a fresh FreeBSD install and will shortly
join the cluster.

==== FreeBSD Advocacy and Education


==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to
protect them. We also provide legal support for the core team to investigate
questions that arise.

Go to link:https://www.FreeBSDfoundation.org[https://www.FreeBSDFoundation.org]
to find more about how we support FreeBSD and how we can help you!
