=== Containers & FreeBSD: Pot, Potluck & Potman

Links: +
link:https://github.com/bsdpot[Pot organization on github] URL: link:https://github.com/bsdpot[https://github.com/bsdpot]

Contact: Luca Pizzamiglio (Pot) <pizzamig@freebsd.org> +
Contact: Stephan Lichtenauer (Potluck) <sl@honeyguide.eu> +
Contact: Michael Gmelin (Potman) <grembo@freebsd.org>

Pot is a jail management tool that link:https://www.freebsd.org/news/status/report-2020-01-2020-03/#pot-and-the-nomad-pot-driver[also supports orchestration through Nomad].

Pot has received some tender, love and care in the form of some fixes which will be released in an update soon.

Potluck aims to be to FreeBSD and Pot what Dockerhub is to Linux and Docker: a repository of Pot flavours and complete container images for usage with Pot and in many cases Nomad.

Many of the core images like link:https://potluck.honeyguide.net/blog/nomad-server/[Nomad], link:https://potluck.honeyguide.net/blog/consul/[Consul] and link:https://potluck.honeyguide.net/blog/vault/[Vault] that can be used to build a private cloud and orchestration platform, but also e.g. link:https://potluck.honeyguide.net/blog/prometheus/[Prometheus] or link:https://potluck.honeyguide.net/blog/postgresql-patroni/[PostgreSQL Patroni], have reached a stable status over the last quarter. +
They are also in production use at a fintech now.

As a first step to improve project visibility and also documentation, a new https://github.com/bsdpot[Pot organization on github] has been set up that in the future will contain pot, its' related projects and documentation. +
There, we plan to release ansible playbooks that allow easily creating a FreeBSD based orchestration environment from scratch based on all these tools.

As always, feedback and patches are welcome.
