# Report month start
START?=		1
# Report month end
STOP?=		3
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	1

# Entries from the various official and semi-official teams
TeamReports= ci.md re.md clusteradm.md graphics.md

# Projects that span multiple categories, from the kernel and userspace to
# the Ports Collection or external projects
Projects= nfsovertls.md kyua.md

# Changes affecting the base system and programs in it
Userland= 

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= bridge.md sigfastblock.md azure.md morello.md ls1046.md ena.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= powerpc.md riscv.md

# Noteworthy changes in the documentation tree or new external
# books/documents
Documentation= weblate.md

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= xfce.md wine.md kde.md go.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= pot.md nomadbsd.md sysctlmibinfo2.md

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
