# Report month start
START?=		1
# Report month end
STOP?=		3
# Report year
YEAR?=		2020
# Report quarter
QUARTER?=	1

# Entries from the various official and semi-official teams
TeamReports= foundation.md core.md re.md clusteradm.md ci.md portmgr.md graphics.md

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= nfsovertls.md kyua.md linuxulator.md syzkaller.md

# Changes affecting the base system and programs in it
Userland= gcc-retirement.md elfctl.md elftoolchain.md

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= bridge.md sigfastblock.md arm64lse.md azure.md morello.md ls1046.md ena.md

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= powerpc.md riscv.md

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation= weblate.md manpages.md

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= xfce.md wine.md kde.md go.md sysctlmibinfo2.md

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= pot.md nomadbsd.md

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
