---
title: "FreeBSD Quarterly Status Report"
sidenav: about
---

= Introduction
:doctype: article
:toc: macro
:toclevels: 2
:icons: font
:!sectnums:
:source-highlighter: rouge
:experimental:
:reports-path: content/en/status/report-2021-01-2021-03

This report covers FreeBSD related projects for the period between June and September, and is the third of four planned reports for 2021.

Yours, +
Daniel Ebdrup Jensen, with status hat on.

'''

toc::[]

'''

[[FreeBSD-Team-Reports]]
== FreeBSD Team Reports

Entries from the various official and semi-official teams, as found in the link:../../administration/[Administration Page].


[[projects]]
== Projects

Projects that span multiple categories, from the kernel and userspace to the Ports Collection or external projects.


[[kernel]]
== Kernel

Updates to kernel subsystems/features, driver support, filesystems, and more.


[[ports]]
== Ports

Changes affecting the Ports Collection, whether sweeping changes that touch most of the tree, or individual ports themselves.

include::erlang.adoc[]

'''

[[documentation]]
== Documentation

Noteworthy changes in the documentation tree, in manpages, or in external books/documents.


[[miscellaneous]]
== Miscellaneous

Objects that defy categorization.


[[third-Party-Projects]]
== Third-Party Projects

Many projects build upon FreeBSD or incorporate components of FreeBSD into their project.
As these projects may be of interest to the broader FreeBSD community, we sometimes include brief updates submitted by these projects in our quarterly report.
The FreeBSD project makes no representation as to the accuracy or veracity of any claims in these submissions.

