---
title: "FreeBSD Quarterly Status Report 3rd Quarter 2021"
sidenav: about
---

= Introduction
:doctype: article
:toc: macro
:toclevels: 2
:icons: font
:!sectnums:
:source-highlighter: rouge
:experimental:
:reports-path: content/en/status/report-2021-01-2021-03

This report covers FreeBSD related projects for the period between June and September, and is the third of four planned reports for 2021.

The third quarter of 2021 was quite active in lots of different areas, so the report covers a bunch of interesting work including but not limited to boot performance, compile-time analysis, hole-punching support, various drivers, ZFS raidz expansion, an update to the sound mixer, and many more.

Regrettably, the status report got a bit delayed, but we hope that the aphorism better late than never can apply here.

Yours, +
Daniel Ebdrup Jensen, with status hat on.

'''

toc::[]

'''

[[FreeBSD-Team-Reports]]
== FreeBSD Team Reports

Entries from the various official and semi-official teams, as found in the link:../../administration/[Administration Page].

include::freebsd-foundation.adoc[]

'''

include::releng.adoc[]

'''

include::clusteradm.adoc[]

'''

include::ci.adoc[]

'''

include::portmgr.adoc[]

'''

include::doceng.adoc[]

'''

include::www.adoc[]

'''

[[projects]]
== Projects

Projects that span multiple categories, from the kernel and userspace to the Ports Collection or external projects.

include::boot-performance.adoc[]

'''

include::git.adoc[]

'''

include::lldb.adoc[]

'''

include::linuxulator.adoc[]

'''

include::mixer.adoc[]

'''

include::openssh.adoc[]

'''

[[kernel]]
== Kernel

Updates to kernel subsystems/features, driver support, filesystems, and more.

include::arm64.adoc[]

'''

include::azure.adoc[]

'''

include::copy_staging.adoc[]

'''

include::ena.adoc[]

'''

include::holepunching.adoc[]

'''

include::intelnet.adoc[]

'''

include::iwlwifi.adoc[]

'''

include::mgb.adoc[]

'''

include::msdosfs_rename.adoc[]

'''

include::raidz-expansion.adoc[]

'''

include::rfc1191.adoc[]

'''

include::rtw88.adoc[]

'''

include::sdhci_acpi.adoc[]

'''

include::stackgap.adoc[]

'''

include::syzkaller.adoc[]

'''

include::ocf-wg.adoc[]

'''

include::vmd.adoc[]

'''

[[ports]]
== Ports

Changes affecting the Ports Collection, whether sweeping changes that touch most of the tree, or individual ports themselves.

include::cpe.adoc[]

'''

include::erlang.adoc[]

'''

include::kde.adoc[]

'''

include::opensearch.adoc[]

'''

include::valgrind.adoc[]

'''

include::wine.adoc[]

'''

include::ztop.adoc[]

'''

[[miscellaneous]]
== Miscellaneous

Objects that defy categorization.

include::current-compilation-time-analysis.adoc[]

'''

[[third-Party-Projects]]
== Third-Party Projects

Many projects build upon FreeBSD or incorporate components of FreeBSD into their project.
As these projects may be of interest to the broader FreeBSD community, we sometimes include brief updates submitted by these projects in our quarterly report.
The FreeBSD project makes no representation as to the accuracy or veracity of any claims in these submissions.

include::gitlab.adoc[]

'''

include::hellosystem.adoc[]

'''

include::pot.adoc[]

'''

include::wg.adoc[]

'''
