== FreeBSD Office team 2021Q1 status report

Link:	 link:https://wiki.freebsd.org/Office[The FreeBSD Office project]  

Contact: FreeBSD Office team ML <office@FreeBSD.org>  
Contact: Dima Panov <fluffy@FreeBSD.org>  
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org>  


The FreeBSD Office team works on a number of office-related software suites 
and tools such as OpenOffice and LibreOffice.

Work during this quarter focused on providing the latest stable release of 
LibreOffice suite and companion apps to all FreeBSD users.

Latest and quarterly ports branches got a new branch (7.1) of the LibreOffice suite
and updated to 7.1.1 release.

Meanwhile, our link:https://github.org/freebsd/freebsd-ports-libreoffice[WIP repository]
got back a working CI instance again, thanks to Li-Wen Hsu.

We are looking for people to help the project.
The link:https://bugs.freebsd.org/bugzilla/buglist.cgi?bug_status=open&email1=office%40FreeBSD.org&emailassigned_to1=1&emailcc1=1&emailreporter1=1&emailtype1=substring&query_format=advanced&list_id=374316[open bugs list]
contains all filed issues which need some attention.
Patches, comments and objections are always welcome in the mailing list and bugzilla.

