== sysctl improvements

Link: https://gitlab.com/alfix/sysctlinfo[sysctlinfo] +
Link: https://gitlab.com/alfix/sysctlbyname-improved[sysctlbyname-improved] +
Link: https://git.io/Jm9x7[BSDCan 2020 - sysctlinfo questions] +
Link: https://gitlab.com/alfix/sysctl-libnv[sysctl-libnv] +
Link: https://gitlab.com/alfix/sysctlmibinfo2[sysctlmibinfo2] +
Link: https://gitlab.com/alfix/sysctlview[sysctlview] +
Link: https://gitlab.com/alfix/nsysctl[nsysctl]

Contact: Alfonso Sabato Siciliano <alfonso.siciliano@email.com>

The sysctl system call and the wrapper sysctl utility can get and set the
system state at runtime, the kernel exposes the available parameters as objects
of a Management Information Base.
After a recent system update with a CURRENT-GENERIC configuration, the MIB has
exceeded ten thousand objects (both internal nodes and leaves, most in the
vm.uma subtree) on my laptop with a Desktop environment without ZFS.
Furthermore I received tips, ideas, PRs and iusses about sysctl so I have been
motivated to fulfil some improvement, finally I accomplished the suggestions
received during the BSDCan 2020.

*Kernel space:* +
sysctlinfo - port: sysutils/sysctlinfo-kmod - updated to 20210222  +
sysctlinfo is an interface to visit the MIB and to retrieve info about an
object (description, type, format, flags, and so on).
It is been refactored so the new version is almost 100% more efficient to
explore the MIB and to pass all info about an object to userland. Moreover new
features are been implemented: to get more info about an object, to avoid extra
computation in userland and to improve the compatibilty with the current
undocumented interface.

sysctlbyname-improved - port: sysutils/sysctlbyname-improved-kmod -
updated to 20210223  +
sysctlbyname-improved is an extension of sysctlinfo to handle an object name
with some empty string level or extetended to pass an input to the handler of a
CTLTYPE_NODE; it is been updated to take advantages of the improvements (mainly
efficiency) of sysctlinfo.

sysctl-libnv, this project provides an implementation and an example to build a
sysctl object with an nvlist value, to know more about nvlist
https://man.freebsd.org/libnv/9. Properly a new sysctl handler is been defined:
it is sufficient create a nvlist and to pass it to a macro then the system call
uses the new handler to pass the nvlist to the userland and the nsysctl utility
can manage the opject value.

The following tools are been updated to give advantages from new kernel features
and improvements.

*Library:* +
sysctlmibinfo2 - port: devel/libsysctlmibinfo2 - updated to 2.0.1 +
Primarily the sysctlmibinfo2 library wraps the low level interfaces described
above, moreover it defines a struct sysctlmif_object with the property of an
object and provides a convenient API to build data structures of
sysctlmif_object (for example: a subtree, a list of a list of a Depth First
Traversal, and so on); therefore it is useful to handle an object correctly
and/or to build a sysctl-like utility.

Obviously sysctlmibinfo2 benefits of the features of sysctlinfo: handles OIDs up
to CTL_MAXNAME levels, supports the Capability Mode, can seek an object matching
its name (avoiding to explore the MIB just to find the corresponding OID),
gets all info about an object in a time and manages a special name via
sysctlbyname-improved.

The version 2.0.1 takes the new advantages from the kernel improvements:
improved efficiency to build a sysctlmif_object and new features to get info
about an object: "handler" and "nextbyname".
The new functions are: sysctlmif_hashandler() and sysctlmif_hashandlerbyname()
to know is an object has a defined kernel handler, sysctlmif_nextnodebyname()
and sysctlmif_nextleafbyname() to explore the MIB, sysctlmif_leaves() and
sysctlmif_leavesbyname() to build structures of only-leaves (properly they build
a list with the descending leaves of a node, it useful because the internal
nodes has not a value).

*Documentation:* +
The APIs decribed above (both kernel and userspace) are really easy:
"sysctl -aN", "sysctl -d kern.ostype", etc., can be implemented by few lines of
code. Nevertheless each project provides a README, with Introduction, Getting
started, Features, API, Real world use cases, FAQ and examples in the Public
Domain to build new projects. Of course the manuals and examples have recently
been updated.

*Utilities:* +
sysctlview - port: deskutils/sysctlview - updated to 2.1 +
The first version of sysctlview was just a graphical representation of the MIB,
now it could be considered a GUI version of the sysctl utility.
This utility exploits the object serialization of sysctlinfo, indeed, it is not
feasible to compel the kernel to find many time the same object to retrieve all
its properties considering the current MIB size.
Thanks to user feedbacks the new version improves the GUI is been improved, for
example sorting by clicking a column title, moreover the "Handler" entry is been
added in the "Object" window, it is useful to know if an object has a value or
if the OID of a CTLTYPE_NODE can be extended.

nsysctl - port: sysutils/nsysctl - updated to 2.0 +
nsysctl is a terminal version of sysctlview, the output is explicitly indicated
by the options and is printed via libxo in human and machine readable formats,
moreover some string value is parsed to display structured output.
The options are not mutually exclusive and allow to show the properties of a
parameter so nsysctl is useful to know the info to handle a sysctl object
without to find its implementation, for example: is Multiprocessor safe?
Is available in Capability mode? Is the OID extendible? Does the integer
represent a kelvin? Has a value? What is the label? And so on.
The new version supports libnv, it is useful to manage a non-primitive data
type avoiding, at least in the future, hardcode of a generic opaque type.
Finally the new features of sysctlinfo allow to use nsysctl to debug the MIB
without a kernel recompilation with SYSCTL_DEBUG.
Note, the project provides a tutorial to describe every features.
