=== drm-kmod upgrade for Alder-Lake i915 graphics

Links: +
link:https://github.com/christian-moerz/drm-kmod[GitHub site] URL:
link:https://github.com/christian-moerz/drm-kmod[https://github.com/christian-moerz/drm-kmod]

Contact: Christian Moerz <freebsd@ny-central.org>

Recent graphics chipsets support in FreeBSD is made possible by
porting linux based graphics drivers to FreeBSD's linuxkpi
layer. The drm-kmod project has continuously pushed forward to bring a
more recent code base to FreeBSD. This is certainly a difficult task,
particularly because linux code does not run on linuxkpi without some
additional patch work.

With the recent release of Intel's Alder Lake CPUs and integrated
graphics, the gap between drm-kmod's code base and linux drivers
widened.

drm-kmod's code base was now updated to integrate current linux
drivers for 12th gen Intel CPUs. The work is still ongoing.

There are a few limitations, particularly in contrast to the more
general drm-kmod base:

* development is focused on 14.0 SNAPSHOT, since everything is based
on the main branch of the original drm-kmod project
* focused only on i915; amd and radeon support was completely removed
* patches were brought over from freedesktop/drm-intel
link:https://github.com/freedesktop/drm-intel[freedesktop/drm-intel]
* it compiles, finally (as of December 27, 2022)
* at the moment, the i915kms driver is not functional yet
* privacy screen features are excluded from code on GitHub; they are
ported as well already but were removed for debugging purposes and
hence are not in the public release yet

At the moment, the code is in a loadable state but needs debugging,
which so far has proven quite difficult.

Kernel debugger access was mostly unsuccessful, because the current
development state leads to a system freeze. Troubleshooting the system
state is also hindered by screen state being reset by the driver.

An internal code branch was littered with printf and panic statements
to pinpoint the cause of system freezes but has not yet delivered
viable results.

Initial tests produced indications, that some mutex-lock/sleep
combinations are causing issues; obviously, these were likely
introduced during the effort of porting linux code to FreeBSD.
While a "hung" system state can be reproducibly created, if one
managed to raise ddb, it showed no locks except for the giant lock.

It will likely require remote debugging, possibly in
combination with reviewing patches for possible suspects that
introduced the issues.

The work that remains for the moment:
* Debug system freezes, via remote debug, savecore, ddb, or kgdb
* Review code changes for possible introduction of deadlocks
