# Report month start
START?=	10
# Report month end
STOP?=	12
# Report year
YEAR?=	2022
# Report quarter
QUARTER?=	4

# Entries from the various official and semi-official teams
TeamReports= freebsd-foundation.adoc releng.adoc clusteradm.adoc ci.adoc portmgr.adoc

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects=

# Changes affecting the base system and programs in it
Userland=

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel=

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures=

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation=	doceng.adoc

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports=

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty=

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
