# Report month start
START?=	10
# Report month end
STOP?=	12
# Report year
YEAR?=	2022
# Report quarter
QUARTER?=	4

# Entries from the various official and semi-official teams
TeamReports= core.adoc freebsd-foundation.adoc releng.adoc clusteradm.adoc ci.adoc portmgr.adoc status.adoc

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= vessel-status-report.adoc NFS-in-prisons.adoc pytest-for-atf.adoc

# Changes affecting the base system and programs in it
Userland= openssh.adoc

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= ufs_snapshots.adoc wifi.adoc netlink.adoc ddb_ctf.adoc

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= cheribsd.adoc golang_riscv64.adoc

# Updating cloud-specific features and bringing in support for new
# cloud platforms
Cloud= cloud-init.adoc openstack-on-freebsd.adoc

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation=	doceng.adoc

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= FreshPorts.adoc portsdb.adoc xfce.adoc pantheon.adoc budgie.adoc gcc.adoc biology.adoc

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= pot.adoc

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
