=== FreeBSD Core Team

Contact: FreeBSD Core Team <core@FreeBSD.org>

The FreeBSD Core Team is the governing body of FreeBSD.

==== Completed Items

===== New Core Team Secretary

All members of the Core Team express publicly their gratitude to Muhammad Moinur Rahman (bofh) for serving as the Core Team Secretary for the past two years.

The Core Team approved Sergio Carlavilla (carlavilla) as the new Core Team secretary.

===== Procedure to handle GDPR deletion request

The Core Team has reviewed the procedure to handle GDPR deletions requests with help from Foundation lawysers.
The document is currently being written and will be published after completion.

===== New Privacy Policy

The Core Team is working closely with the FreeBSD Foundation to update the Privacy Policy to properly align with current laws and practices found on similar websites such as ours.

===== Bruce memorial plaque

The Core Team unanimously votes to allow the memorial plaque for Bruce mentioning him as co-founder of FreeBSD.

===== EuroBSDCon core team office hour

On Friday, September 16, the new Core Team will be presenting at EuroBSDCon.
The Core Team would like to introduce themselves and talk a bit about our plans for this term.
Attendees are given the chance to ask questions.

==== Commit bits

Core approved the restore of the source commit bit for Konrad Witaszczyk (def@).
Right now Konrad is working at Cambridge University, where he is responsible for developing CheriBSD.
