# Report month start
START?=	7
# Report month end
STOP?=	9
# Report year
YEAR?=	2022
# Report quarter
QUARTER?=	3

# Entries from the various official and semi-official teams
TeamReports= core.adoc freebsd-foundation.adoc releng.adoc clusteradm.adoc ci.adoc portmgr.adoc

# Projects that span multiple categories, from the kernel, and userspace to
# the Ports Collection or external projects
Projects= openstack-on-freebsd.adoc cloud-init.adoc

# Changes affecting the base system and programs in it
Userland= bhyve-debug-server-enhancements.adoc pjdfstest.adoc lldb.adoc kinst.adoc

# Updates to kernel subsystems/features, driver support, filesystems,
# and more
Kernel= ena.adoc wtap.adoc iwlwifi.adoc wifi.adoc ufs_snapshots.adoc

# Updating platform-specific features and bringing in support for new
# hardware platforms
Architectures= firecracker.adoc

# Noteworthy changes in the documentation tree, man-pages, or new
# external books/documents
Documentation=	doceng.adoc

# Changes affecting the Ports Collection, whether sweeping changes that
# touch most of the tree, or individual ports themselves
Ports= calendar-data.adoc kde.adoc gcc.adoc lsof.adoc

# Third party project built on FreeBSD, but not part of the FreeBSD
# project itself
ThirdParty= pot.adoc

# Objects that defy categorization
Miscellaneous=

.include <../tools/Makefile>
